### ISSUE TITLE
LOGO doesn't appear.

### ISSUE THREAD

**Issue by djmips** [slightlynybbled/resume#3]
Clicked on your resume and the logo.png was MIA.
I'm not sure how it's all supposed to look but it feels like it's either meant to be WEB 1.0 which is fine but the broken image made me wonder if more wasn't broken.

**Comment by slightlynybbled** [comment]
Thanks for the info.

You were right, something is broken.  I have never found long-term stability using github pages so I moved the link to [readthedocs.io](https://slightlynybbledresume.readthedocs.io/en/latest/).  Sphinx just looks better there.

**Comment by djmips** [comment]
That does look much better.
